---
networks:
  infra:
    name: bridge_infra
    driver: bridge
    ipam:
      config:
        - subnet:  10.0.0.0/16
          gateway: 10.0.0.1

  monitoring: 
    driver: bridge 


services:
  ##
  ### Core services
  ##
  # gitlab:
  #   image: gitlab/gitlab-ee:latest
  #   container_name: gitlab
  #   restart: unless-stopped
  #   hostname: gitlab.i3do.dev
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://gitlab.i3do.dev'
  #       letsencrypt['enable'] = true
  #       nginx['redirect_http_to_https'] = true
  #   ports:
  #     - '22:22'
  #   volumes:
  #     - '/srv/gitlab/config:/etc/gitlab'
  #     - '/srv/gitlab/ssl:/etc/gitlab/ssl'
  #     - '/srv/gitlab/logs:/var/log/gitlab'
  #     - '/srv/gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'
  #   networks:
  #     infra:
  #       ipv4_address: 10.0.0.2
  #   dns: 8.8.8.8

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    hostname: s3.i3do.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - './srv/minio:/data'
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server --console-address ":9001" /data
    networks:
      infra:
        ipv4_address: 10.0.0.4
    dns: 8.8.8.8



  ##
  ### Monitoring
  ##
  node-exporter: 
    image: prom/node-exporter:latest 
    container_name: node-exporter 
    restart: unless-stopped 
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - monitoring 

  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus 
    restart: unless-stopped 
    user: "1000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes: 
      - ./settings/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./srv/prometheus:/prometheus 
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus' 
      - '--web.console.libraries=/etc/prometheus/console_libraries' 
      - '--web.console.templates=/etc/prometheus/consoles' 
      - '--web.enable-lifecycle' 
    ports: 
      - 9090:9090 
    networks: 
      - monitoring 

  grafana: 
    image: grafana/grafana:latest 
    container_name: grafana 
    restart: unless-stopped 
    user: "1000"
    ports: 
      - 3000:3000 
    volumes: 
      - ./srv/grafana:/var/lib/grafana 
    networks: 
      - monitoring 
